# Generated by Django 5.0.2 on 2025-04-26 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_status'),
        ('prescriptions', '0003_alter_prescription_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
