# Generated by Django 5.0.2 on 2025-04-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_alter_prescription_patient_delete_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescriber_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='drug_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
